name: frontend

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - vue
          - react

    defaults:
      run:
        working-directory: ${{ matrix.package }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: ${{ matrix.package }}/package-lock.json

      - run: npm ci

      - run: npm run lint:check

      - run: npm run eslint

      - run: npm run build

      - run: npm run type-check
